//! GENERATED by tools/gentl.py from a Telegram API .tl schema.
//! Field order and flags come straight from the schema — do not hand-edit.
//! Unread/unused fields keep their reads so the stream stays aligned.
#![allow(dead_code, unused_variables, unused_mut)]
#![allow(unused_imports)]
#![allow(clippy::enum_variant_names)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::needless_option_as_deref)]
#![allow(clippy::large_enum_variant)]
// Schema-shaped wire code is generated, never hand-maintained: the
// strict gate's pedantic/nursery groups and the byte-wrangling
// classes (casts, wire-int narrowing) are silenced wholesale here
// instead of in every handwritten module.
#![allow(clippy::pedantic, clippy::nursery)]
#![allow(clippy::as_conversions, clippy::cast_sign_loss)]
#![allow(clippy::cast_possible_truncation, clippy::cast_possible_wrap)]

use super::chat_gen::{
    BaseTheme, Chat, ChatAdminRights, ChatBannedRights, ChatPhoto, DataJSON, DocumentAttribute,
    Game, GeoPointAddress, InputGame, InputGroupCall, InputMedia, InputNotifyPeer, InputWallPaper,
    InputWebDocument, Invoice, LabeledPrice, MediaArea, MediaAreaCoordinates, MessageExtendedMedia,
    MessagesEmojiGameOutcome, NotificationSound, Page, PageBlock, PageCaption, PageListItem,
    PageListOrderedItem, PageRelatedArticle, PageTableCell, PageTableRow, PeerNotifySettings, Poll,
    PollAnswer, PollAnswerVoters, PollResults, PrivacyRule, Reaction, ReactionCount, RichText,
    StarGift, StarGiftAttribute, StarGiftAttributeRarity, StarGiftBackground, StarsAmount,
    StoryFwdHeader, StoryItem, StoryViews, ThemeSettings, TodoCompletion, TodoItem, TodoList,
    VideoSize, WallPaper, WallPaperSettings, WebPage, WebPageAttribute,
};
use super::input_gen::{
    InputChannel, InputDocument, InputFile, InputGeoPoint, InputPeer, InputPhoto, InputStickerSet,
    InputUser, MaskCoords, TextWithEntities,
};
use super::message_gen::{DraftMessage, InputReplyTo, MessageEntity, MessageMedia, SuggestedPost};
use super::peer_gen::Peer;
use super::photo_gen::{Document, GeoPoint, Photo, PhotoSize, WebDocument};
use super::user_gen::{EmojiStatus, PeerColor, RecentStory, RestrictionReason, Username};
use crate::error::{Error, Result};
use crate::serialize::TLReader;
use crate::types::{AccessHash, ChannelId, ChatId, DocumentId, MsgId, PhotoId, UserId};

pub const TOP_PEER_CATEGORY_PEERS_ID: u32 = 0xfb834291;
pub const TOP_PEER_CATEGORY_BOTS_GUEST_CHAT_ID: u32 = 0x6c24f3dd;
pub const TOP_PEER_CATEGORY_BOTS_APP_ID: u32 = 0xfd9e7bec;
pub const TOP_PEER_CATEGORY_FORWARD_CHATS_ID: u32 = 0xfbeec0f0;
pub const TOP_PEER_CATEGORY_FORWARD_USERS_ID: u32 = 0xa8406ca9;
pub const TOP_PEER_CATEGORY_PHONE_CALLS_ID: u32 = 0x1e76a78c;
pub const TOP_PEER_CATEGORY_CHANNELS_ID: u32 = 0x161d9628;
pub const TOP_PEER_CATEGORY_GROUPS_ID: u32 = 0xbd17a14a;
pub const TOP_PEER_CATEGORY_CORRESPONDENTS_ID: u32 = 0x0637b7ed;
pub const TOP_PEER_CATEGORY_BOTS_INLINE_ID: u32 = 0x148677e2;
pub const TOP_PEER_CATEGORY_BOTS_PM_ID: u32 = 0xab661b5b;
pub const TOP_PEER_ID: u32 = 0xedcdc05b;
pub const DIALOG_FOLDER_ID: u32 = 0x71bd134c;
pub const FOLDER_ID: u32 = 0xff544e65;
pub const DIALOG_ID: u32 = 0xfc89f7f3;

/// `topPeerCategoryPeers#fb834291 = TopPeerCategoryPeers`
#[derive(Debug, Clone, PartialEq)]
pub struct TopPeerCategoryPeers {
    pub category: TopPeerCategory,
    pub count: i32,
    pub peers: Vec<TopPeer>,
}

impl TopPeerCategoryPeers {
    pub fn read_from(r: &mut TLReader) -> Result<Self> {
        let ctor = r.read_u32()?;
        if ctor != TOP_PEER_CATEGORY_PEERS_ID {
            return Err(Error::Serialization(format!(
                "expected topPeerCategoryPeers, got {ctor:#x}"
            )));
        }
        let category = TopPeerCategory::read_from(r)?;
        let count = r.read_i32()?;
        let n = r.read_vector_header()?;
        let mut peers = Vec::with_capacity(n.max(0) as usize);
        for _ in 0..n {
            peers.push(TopPeer::read_from(r)?);
        }
        Ok(TopPeerCategoryPeers {
            category,
            count,
            peers,
        })
    }
}

/// Union `TopPeerCategory` (10 constructors).
#[derive(Debug, Clone, PartialEq)]
pub enum TopPeerCategory {
    /// `topPeerCategoryBotsGuestChat#6c24f3dd`
    TopPeerCategoryBotsGuestChat,
    /// `topPeerCategoryBotsApp#fd9e7bec`
    TopPeerCategoryBotsApp,
    /// `topPeerCategoryForwardChats#fbeec0f0`
    TopPeerCategoryForwardChats,
    /// `topPeerCategoryForwardUsers#a8406ca9`
    TopPeerCategoryForwardUsers,
    /// `topPeerCategoryPhoneCalls#1e76a78c`
    TopPeerCategoryPhoneCalls,
    /// `topPeerCategoryChannels#161d9628`
    TopPeerCategoryChannels,
    /// `topPeerCategoryGroups#bd17a14a`
    TopPeerCategoryGroups,
    /// `topPeerCategoryCorrespondents#0637b7ed`
    TopPeerCategoryCorrespondents,
    /// `topPeerCategoryBotsInline#148677e2`
    TopPeerCategoryBotsInline,
    /// `topPeerCategoryBotsPM#ab661b5b`
    TopPeerCategoryBotsPM,
}

impl TopPeerCategory {
    pub fn read_from(r: &mut TLReader) -> Result<Self> {
        let ctor = r.read_u32()?;
        match ctor {
            TOP_PEER_CATEGORY_BOTS_GUEST_CHAT_ID => {
                Ok(TopPeerCategory::TopPeerCategoryBotsGuestChat {})
            }
            TOP_PEER_CATEGORY_BOTS_APP_ID => Ok(TopPeerCategory::TopPeerCategoryBotsApp {}),
            TOP_PEER_CATEGORY_FORWARD_CHATS_ID => {
                Ok(TopPeerCategory::TopPeerCategoryForwardChats {})
            }
            TOP_PEER_CATEGORY_FORWARD_USERS_ID => {
                Ok(TopPeerCategory::TopPeerCategoryForwardUsers {})
            }
            TOP_PEER_CATEGORY_PHONE_CALLS_ID => Ok(TopPeerCategory::TopPeerCategoryPhoneCalls {}),
            TOP_PEER_CATEGORY_CHANNELS_ID => Ok(TopPeerCategory::TopPeerCategoryChannels {}),
            TOP_PEER_CATEGORY_GROUPS_ID => Ok(TopPeerCategory::TopPeerCategoryGroups {}),
            TOP_PEER_CATEGORY_CORRESPONDENTS_ID => {
                Ok(TopPeerCategory::TopPeerCategoryCorrespondents {})
            }
            TOP_PEER_CATEGORY_BOTS_INLINE_ID => Ok(TopPeerCategory::TopPeerCategoryBotsInline {}),
            TOP_PEER_CATEGORY_BOTS_PM_ID => Ok(TopPeerCategory::TopPeerCategoryBotsPM {}),
            other => Err(Error::Serialization(format!(
                "unknown TopPeerCategory constructor {other:#x}"
            ))),
        }
    }
}

/// `topPeer#edcdc05b = TopPeer`
#[derive(Debug, Clone, PartialEq)]
pub struct TopPeer {
    pub peer: Peer,
    pub rating: f64,
}

impl TopPeer {
    pub fn read_from(r: &mut TLReader) -> Result<Self> {
        let ctor = r.read_u32()?;
        if ctor != TOP_PEER_ID {
            return Err(Error::Serialization(format!(
                "expected topPeer, got {ctor:#x}"
            )));
        }
        let peer = Peer::read_from(r)?;
        let rating = f64::from_bits(r.read_u64()?);
        Ok(TopPeer { peer, rating })
    }
}

/// Union `Dialog` (2 constructors).
#[derive(Debug, Clone, PartialEq)]
pub enum Dialog {
    /// `dialogFolder#71bd134c`
    DialogFolder {
        flags: i32,
        pinned: bool,
        folder: Folder,
        peer: Peer,
        top_message: i32,
        unread_muted_peers_count: i32,
        unread_unmuted_peers_count: i32,
        unread_muted_messages_count: i32,
        unread_unmuted_messages_count: i32,
    },
    /// `dialog#fc89f7f3`
    Dialog {
        flags: i32,
        pinned: bool,
        unread_mark: bool,
        view_forum_as_messages: bool,
        peer: Peer,
        top_message: i32,
        read_inbox_max_id: i32,
        read_outbox_max_id: i32,
        unread_count: i32,
        unread_mentions_count: i32,
        unread_reactions_count: i32,
        unread_poll_votes_count: i32,
        notify_settings: PeerNotifySettings,
        pts: Option<i32>,
        draft: Option<DraftMessage>,
        folder_id: Option<i32>,
        ttl_period: Option<i32>,
    },
}

impl Dialog {
    pub fn read_from(r: &mut TLReader) -> Result<Self> {
        let ctor = r.read_u32()?;
        match ctor {
            DIALOG_FOLDER_ID => {
                let flags = r.read_i32()?;
                let pinned = flags & (1 << 2) != 0;
                let folder = Folder::read_from(r)?;
                let peer = Peer::read_from(r)?;
                let top_message = r.read_i32()?;
                let unread_muted_peers_count = r.read_i32()?;
                let unread_unmuted_peers_count = r.read_i32()?;
                let unread_muted_messages_count = r.read_i32()?;
                let unread_unmuted_messages_count = r.read_i32()?;
                Ok(Dialog::DialogFolder {
                    flags,
                    pinned,
                    folder,
                    peer,
                    top_message,
                    unread_muted_peers_count,
                    unread_unmuted_peers_count,
                    unread_muted_messages_count,
                    unread_unmuted_messages_count,
                })
            }
            DIALOG_ID => {
                let flags = r.read_i32()?;
                let pinned = flags & (1 << 2) != 0;
                let unread_mark = flags & (1 << 3) != 0;
                let view_forum_as_messages = flags & (1 << 6) != 0;
                let peer = Peer::read_from(r)?;
                let top_message = r.read_i32()?;
                let read_inbox_max_id = r.read_i32()?;
                let read_outbox_max_id = r.read_i32()?;
                let unread_count = r.read_i32()?;
                let unread_mentions_count = r.read_i32()?;
                let unread_reactions_count = r.read_i32()?;
                let unread_poll_votes_count = r.read_i32()?;
                let notify_settings = PeerNotifySettings::read_from(r)?;
                let pts = if flags & (1 << 0) != 0 {
                    let pts = r.read_i32()?;
                    Some(pts)
                } else {
                    None
                };
                let draft = if flags & (1 << 1) != 0 {
                    let draft = DraftMessage::read_from(r)?;
                    Some(draft)
                } else {
                    None
                };
                let folder_id = if flags & (1 << 4) != 0 {
                    let folder_id = r.read_i32()?;
                    Some(folder_id)
                } else {
                    None
                };
                let ttl_period = if flags & (1 << 5) != 0 {
                    let ttl_period = r.read_i32()?;
                    Some(ttl_period)
                } else {
                    None
                };
                Ok(Dialog::Dialog {
                    flags,
                    pinned,
                    unread_mark,
                    view_forum_as_messages,
                    peer,
                    top_message,
                    read_inbox_max_id,
                    read_outbox_max_id,
                    unread_count,
                    unread_mentions_count,
                    unread_reactions_count,
                    unread_poll_votes_count,
                    notify_settings,
                    pts,
                    draft,
                    folder_id,
                    ttl_period,
                })
            }
            other => Err(Error::Serialization(format!(
                "unknown Dialog constructor {other:#x}"
            ))),
        }
    }
}

/// `folder#ff544e65 = Folder`
#[derive(Debug, Clone, PartialEq)]
pub struct Folder {
    pub flags: i32,
    pub autofill_new_broadcasts: bool,
    pub autofill_public_groups: bool,
    pub autofill_new_correspondents: bool,
    pub id: i32,
    pub title: String,
    pub photo: Option<ChatPhoto>,
}

impl Folder {
    pub fn read_from(r: &mut TLReader) -> Result<Self> {
        let ctor = r.read_u32()?;
        if ctor != FOLDER_ID {
            return Err(Error::Serialization(format!(
                "expected folder, got {ctor:#x}"
            )));
        }
        let flags = r.read_i32()?;
        let autofill_new_broadcasts = flags & (1 << 0) != 0;
        let autofill_public_groups = flags & (1 << 1) != 0;
        let autofill_new_correspondents = flags & (1 << 2) != 0;
        let id = r.read_i32()?;
        let title = String::from_utf8(r.read_bytes()?)?;
        let photo = if flags & (1 << 3) != 0 {
            let photo = ChatPhoto::read_from(r)?;
            Some(photo)
        } else {
            None
        };
        Ok(Folder {
            flags,
            autofill_new_broadcasts,
            autofill_public_groups,
            autofill_new_correspondents,
            id,
            title,
            photo,
        })
    }
}
