//! TL type library for the Telegram API.
//!
//! Schema-shaped types are GENERATED by `tools/gentl.py`
//! (`--compat --domain <name>`) into `<domain>_gen.rs` files;
//! they are the single source of truth for wire format. Hand-
//! written modules keep curated aggregates and helper impls
//! (`MessageFull`, `FileLocation`, accessor methods, the update
//! dispatcher's `Update` surface).

mod builders;
mod compat_impls;
mod chat_gen;
mod constructors;
mod dialog;
mod dialog_gen;
mod ids;
mod input_gen;
mod message;
mod message_gen;
mod peer_gen;
mod photo;
mod photo_gen;
mod reply_markup_gen;
mod replies;
mod reply_types;
mod updates;
mod updates_gen;
mod user;
mod user_gen;

/// Generated request builders used for wire-equivalence regression
/// tests against the handwritten rpc.rs builders.
pub mod gen_fns;

pub use input_gen::*;
pub use peer_gen::*;
pub use user_gen::*;
pub use chat_gen::{Chat, ChatFull, ChatAdminRights, ChatBannedRights,
                   ChatParticipant, ChatParticipants, ExportedChatInvite, WebPage};
pub use dialog_gen::*;
pub use photo_gen::*;
pub use reply_markup_gen::*;
pub use builders::*;
pub use constructors::*;
pub use ids::*;
pub use message::*;
pub use replies::*;
pub use reply_types::*;

// Curated names owned by the private impl modules — the gen modules do
// not define these.
pub use photo::{FileLocation, stripped_thumb_jpeg};
pub use message_gen::{
    DraftMessage, FactCheck, MessageFwdHeader, MessageReactions, MessageReplies,
    MessagesInvitedUsers, SuggestedPost,
};
pub use updates_gen::Updates as GenUpdates;
pub use dialog::{Dialog, Dialogs, State, Messages};
pub use updates::{Difference, ChannelDifference, Updates, Update};
pub use updates::skip_peer_notify_settings_public;
pub use updates::{read_chat_vector_public, read_user_vector_public};

#[cfg(test)]
mod tests;

/// Layer-225 schema constant lookup used by the regression test:
/// maps a constructors.rs name to the generated `*_ID` value.
#[cfg(test)]
pub(crate) fn gen_const(name: &str) -> Option<u32> {
    use chat_gen as c;
    use input_gen as i;
    use message_gen as m;
    use user_gen as u;
    use dialog_gen as d;
    use reply_markup_gen as rm;
    Some(match name {
        "USER" => u::USER_ID,
        "USER_EMPTY" => u::USER_EMPTY_ID,
        "CHAT" => c::CHAT_ID,
        "CHAT_EMPTY" => c::CHAT_EMPTY_ID,
        "CHAT_FORBIDDEN" => c::CHAT_FORBIDDEN_ID,
        "CHANNEL" => c::CHANNEL_ID,
        "MESSAGE" => m::MESSAGE_ID,
        "MESSAGE_EMPTY" => m::MESSAGE_EMPTY_ID,
        "MESSAGE_SERVICE" => m::MESSAGE_SERVICE_ID,
        "MESSAGE_MEDIA_PHOTO" => m::MESSAGE_MEDIA_PHOTO_ID,
        "MESSAGE_MEDIA_DOCUMENT" => m::MESSAGE_MEDIA_DOCUMENT_ID,
        "DIALOG" => d::DIALOG_ID,
        "PEER_USER" => peer_gen::PEER_USER_ID,
        "PEER_CHAT" => peer_gen::PEER_CHAT_ID,
        "PEER_CHANNEL" => peer_gen::PEER_CHANNEL_ID,
        "INPUT_PEER_USER" => i::INPUT_PEER_USER_ID,
        "INPUT_PEER_CHAT" => i::INPUT_PEER_CHAT_ID,
        "INPUT_PEER_CHANNEL" => i::INPUT_PEER_CHANNEL_ID,
        "INPUT_PEER_SELF" => i::INPUT_PEER_SELF_ID,
        "INPUT_USER" => i::INPUT_USER_ID,
        "INPUT_USER_SELF" => i::INPUT_USER_SELF_ID,
        "INPUT_CHANNEL" => i::INPUT_CHANNEL_ID,
        "INPUT_FILE" => i::INPUT_FILE_ID,
        "INPUT_FILE_BIG" => i::INPUT_FILE_BIG_ID,
        "INPUT_DOCUMENT" => i::INPUT_DOCUMENT_ID,
        "INPUT_DOCUMENT_EMPTY" => i::INPUT_DOCUMENT_EMPTY_ID,
        "KEYBOARD_BUTTON" => rm::KEYBOARD_BUTTON_ID,
        "USER_STATUS_ONLINE" => u::USER_STATUS_ONLINE_ID,
        "USER_STATUS_OFFLINE" => u::USER_STATUS_OFFLINE_ID,
        "USER_PROFILE_PHOTO" => u::USER_PROFILE_PHOTO_ID,
        "PEER_NOTIFY_SETTINGS" => c::PEER_NOTIFY_SETTINGS_ID,
        "AUTH_AUTHORIZATION" => m::AUTH_AUTHORIZATION_ID,
        "AUTH_SIGN_IN" => m::AUTH_SIGN_IN_ID,
        _ => return None,
    })
}
