//! GENERATED by tools/gentl.py from a Telegram API .tl schema.
//! Field order and flags come straight from the schema — do not hand-edit.
//! Unread/unused fields keep their reads so the stream stays aligned.
#![allow(dead_code, unused_variables, unused_mut)]
#![allow(unused_imports)]
#![allow(clippy::enum_variant_names)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::needless_option_as_deref)]
#![allow(clippy::large_enum_variant)]
// Schema-shaped wire code is generated, never hand-maintained: the
// strict gate's pedantic/nursery groups and the byte-wrangling
// classes (casts, wire-int narrowing) are silenced wholesale here
// instead of in every handwritten module.
#![allow(clippy::pedantic, clippy::nursery)]
#![allow(clippy::as_conversions, clippy::cast_sign_loss)]
#![allow(clippy::cast_possible_truncation, clippy::cast_possible_wrap)]

use crate::error::{Error, Result};
use crate::serialize::TLReader;
use crate::types::{AccessHash, ChannelId, ChatId, DocumentId, MsgId, PhotoId, UserId};

pub const PEER_CHANNEL_ID: u32 = 0xa2a5371e;
pub const PEER_CHAT_ID: u32 = 0x36c6019a;
pub const PEER_USER_ID: u32 = 0x59511722;

/// Union `Peer` (3 constructors).
#[derive(Debug, Clone, PartialEq)]
pub enum Peer {
    /// `peerChannel#a2a5371e`
    Channel { channel_id: ChannelId },
    /// `peerChat#36c6019a`
    Chat { chat_id: ChatId },
    /// `peerUser#59511722`
    User { user_id: UserId },
    /// Client-side sentinel — not a wire value.
    None,
}

impl Peer {
    pub fn read_from(r: &mut TLReader) -> Result<Self> {
        let ctor = r.read_u32()?;
        match ctor {
            PEER_CHANNEL_ID => {
                let channel_id = r.read_i64()?;
                let channel_id = ChannelId(channel_id);
                Ok(Peer::Channel { channel_id })
            }
            PEER_CHAT_ID => {
                let chat_id = r.read_i64()?;
                let chat_id = ChatId(chat_id);
                Ok(Peer::Chat { chat_id })
            }
            PEER_USER_ID => {
                let user_id = r.read_i64()?;
                let user_id = UserId(user_id);
                Ok(Peer::User { user_id })
            }
            other => Err(Error::Serialization(format!(
                "unknown Peer constructor {other:#x}"
            ))),
        }
    }
}
