//! GENERATED by tools/gentl.py from a Telegram API .tl schema.
//! Field order and flags come straight from the schema — do not hand-edit.
//! Unread/unused fields keep their reads so the stream stays aligned.
#![allow(dead_code, unused_variables, unused_mut)]
#![allow(clippy::enum_variant_names)]
#![allow(unused_imports)]
#![allow(clippy::clone_on_copy)]
#![allow(clippy::needless_option_as_deref)]
#![allow(clippy::large_enum_variant)]
// Schema-shaped wire code is generated, never hand-maintained: the
// strict gate's pedantic/nursery groups and the byte-wrangling
// classes (casts, wire-int narrowing) are silenced wholesale here
// instead of in every handwritten module.
#![allow(clippy::pedantic, clippy::nursery)]
#![allow(clippy::as_conversions, clippy::cast_sign_loss)]
#![allow(clippy::cast_possible_truncation, clippy::cast_possible_wrap)]

use super::chat_gen::{ChatAdminRights, InlineButtonType, InlineQueryPeerType};
use super::input_gen::{InputPeer, InputUser};
use super::message_gen::{
    ButtonType, KeyboardButtonRow, KeyboardButtonStyle, KeyboardInlineButton,
    KeyboardInlineButtonRow, RequestPeerType,
};
use crate::error::{Error, Result};
use crate::serialize::TLReader;
use crate::types::{AccessHash, ChannelId, ChatId, DocumentId, MsgId, PhotoId, UserId};

pub const KEYBOARD_BUTTON_ID: u32 = 0x2f67a72f;
pub const REPLY_INLINE_MARKUP_ID: u32 = 0xb2b15770;
pub const REPLY_KEYBOARD_MARKUP_ID: u32 = 0x85dd99d1;
pub const BOTS_GET_REQUESTED_WEB_VIEW_BUTTON_ID: u32 = 0xbf25b7f3;
pub const REPLY_KEYBOARD_FORCE_REPLY_ID: u32 = 0x86b40b08;
pub const REPLY_KEYBOARD_HIDE_ID: u32 = 0xa03e5b85;

/// `keyboardButton#2f67a72f = KeyboardButton`
#[derive(Debug, Clone, PartialEq)]
pub struct KeyboardButton {
    pub flags: i32,
    pub style: Option<KeyboardButtonStyle>,
    pub text: String,
    pub r#type: ButtonType,
}

impl KeyboardButton {
    pub fn read_from(r: &mut TLReader) -> Result<Self> {
        let ctor = r.read_u32()?;
        if ctor != KEYBOARD_BUTTON_ID {
            return Err(Error::Serialization(format!(
                "expected keyboardButton, got {ctor:#x}"
            )));
        }
        let flags = r.read_i32()?;
        let style = if flags & (1 << 10) != 0 {
            let style = KeyboardButtonStyle::read_from(r)?;
            Some(style)
        } else {
            None
        };
        let text = String::from_utf8(r.read_bytes()?)?;
        let r#type = ButtonType::read_from(r)?;
        Ok(KeyboardButton {
            flags,
            style,
            text,
            r#type,
        })
    }
}

/// Union `ReplyMarkup` (4 constructors).
#[derive(Debug, Clone, PartialEq)]
pub enum ReplyMarkup {
    /// `replyInlineMarkup#b2b15770`
    InlineKeyboard {
        flags: i32,
        force_reply: bool,
        rows: Vec<KeyboardInlineButtonRow>,
    },
    /// `replyKeyboardMarkup#85dd99d1`
    ReplyKeyboard {
        flags: i32,
        resize: bool,
        single_use: bool,
        selective: bool,
        persistent: bool,
        force_reply: bool,
        rows: Vec<KeyboardButtonRow>,
        placeholder: Option<String>,
    },
    /// `replyKeyboardForceReply#86b40b08`
    ForceReply {
        flags: i32,
        single_use: bool,
        selective: bool,
        placeholder: Option<String>,
    },
    /// `replyKeyboardHide#a03e5b85`
    None { flags: i32, selective: bool },
}

impl ReplyMarkup {
    pub fn read_from(r: &mut TLReader) -> Result<Self> {
        let ctor = r.read_u32()?;
        match ctor {
            0x48a30254 => {
                // 223 dialect replyInlineMarkup: rows of keyboardButtonRow#
                // KeyboardButton (H10: sharing the 229 arm read
                // KeyboardInlineButtonRow-shaped bytes and desynced).
                // Consume exactly via the 223-shaped parser, then map
                // each button lossily to the 229 model (text preserved;
                // exotic 223-only button payloads drop to Disabled).
                let n = r.read_vector_header()?;
                let mut rows = Vec::with_capacity(n.max(0) as usize);
                for _ in 0..n {
                    let row = crate::types::gen_fns::KeyboardButtonRow::read_from(r)?;
                    let buttons = row
                        .buttons
                        .into_iter()
                        .map(map_223_button_to_inline)
                        .collect();
                    rows.push(KeyboardInlineButtonRow { buttons });
                }
                Ok(ReplyMarkup::InlineKeyboard {
                    flags: 0,
                    force_reply: false,
                    rows,
                })
            }
            REPLY_KEYBOARD_MARKUP_ID => {
                let flags = r.read_i32()?;
                let resize = flags & (1 << 0) != 0;
                let single_use = flags & (1 << 1) != 0;
                let selective = flags & (1 << 2) != 0;
                let persistent = flags & (1 << 4) != 0;
                let force_reply = flags & (1 << 5) != 0;
                let n = r.read_vector_header()?;
                let mut rows = Vec::with_capacity(n.max(0) as usize);
                for _ in 0..n {
                    rows.push(KeyboardButtonRow::read_from(r)?);
                }
                let placeholder = if flags & (1 << 3) != 0 {
                    let placeholder = String::from_utf8(r.read_bytes()?)?;
                    Some(placeholder)
                } else {
                    None
                };
                Ok(ReplyMarkup::ReplyKeyboard {
                    flags,
                    resize,
                    single_use,
                    selective,
                    persistent,
                    force_reply,
                    rows,
                    placeholder,
                })
            }
            REPLY_KEYBOARD_FORCE_REPLY_ID => {
                let flags = r.read_i32()?;
                let single_use = flags & (1 << 1) != 0;
                let selective = flags & (1 << 2) != 0;
                let placeholder = if flags & (1 << 3) != 0 {
                    let placeholder = String::from_utf8(r.read_bytes()?)?;
                    Some(placeholder)
                } else {
                    None
                };
                Ok(ReplyMarkup::ForceReply {
                    flags,
                    single_use,
                    selective,
                    placeholder,
                })
            }
            REPLY_KEYBOARD_HIDE_ID => {
                let flags = r.read_i32()?;
                let selective = flags & (1 << 2) != 0;
                Ok(ReplyMarkup::None { flags, selective })
            }
            other => Err(Error::Serialization(format!(
                "unknown ReplyMarkup constructor {other:#x}"
            ))),
        }
    }
}

/// Map a 223-dialect `keyboardButton` to the 229 `keyboardInlineButton`
/// model. Text is preserved; action payloads map where a 229 counterpart
/// exists, otherwise the button renders as disabled (H10 conversion is
/// intentionally lossy — the goal is exact byte consumption plus a
/// usable text surface, not full fidelity).
fn map_223_button_to_inline(
    button: crate::types::gen_fns::KeyboardButton,
) -> KeyboardInlineButton {
    use crate::types::gen_fns::KeyboardButton as K;
    use crate::types::chat_gen::InlineButtonType as T;
    let (text, r#type) = match button {
        K::Url { text, url, .. } => (text, T::InlineButtonTypeUrl { url }),
        K::Callback { text, data, .. } => (
            text,
            T::InlineButtonTypeCallback {
                flags: 0,
                requires_password: false,
                data,
            },
        ),
        K::KeyboardButtonBuy { text, .. } => (text, T::InlineButtonTypeBuy),
        K::KeyboardButtonGame { text, .. } => (text, T::InlineButtonTypeGame),
        K::KeyboardButtonCopy { text, copy_text, .. } => {
            (text, T::InlineButtonTypeCopy { copy_text })
        }
        K::KeyboardButtonWebView { text, url, .. }
        | K::KeyboardButtonSimpleWebView { text, url, .. } => {
            (text, T::InlineButtonTypeWebView { url })
        }
        K::KeyboardButtonSwitchInline {
            text,
            query,
            same_peer,
            ..
        } => (
            text,
            T::InlineButtonTypeSwitchInline {
                flags: i32::from(same_peer),
                same_peer,
                query,
                peer_types: None, // lossy: 223 peer-type filters dropped
            },
        ),
        K::KeyboardButtonUserProfile { text, user_id, .. } => {
            (text, T::InlineButtonTypeUserProfile { user_id })
        }
        K::KeyboardButtonUrlAuth { text, url, .. } => {
            (text, T::InlineButtonTypeUrl { url })
        }
        other => (button_text(&other), T::InlineButtonTypeDisabled),
    };
    KeyboardInlineButton {
        flags: 0,
        style: None,
        text,
        r#type,
    }
}

/// Extract the label from any 223 keyboard button variant.
fn button_text(button: &crate::types::gen_fns::KeyboardButton) -> String {
    use crate::types::gen_fns::KeyboardButton as K;
    match button {
        K::KeyboardButtonCopy { text, .. }
        | K::InputKeyboardButtonRequestPeer { text, .. }
        | K::KeyboardButtonRequestPeer { text, .. }
        | K::KeyboardButtonSimpleWebView { text, .. }
        | K::KeyboardButtonWebView { text, .. }
        | K::KeyboardButtonUserProfile { text, .. }
        | K::InputKeyboardButtonUserProfile { text, .. }
        | K::KeyboardButtonRequestPoll { text, .. }
        | K::InputKeyboardButtonUrlAuth { text, .. }
        | K::KeyboardButtonUrlAuth { text, .. }
        | K::KeyboardButtonBuy { text, .. }
        | K::KeyboardButtonGame { text, .. }
        | K::KeyboardButtonSwitchInline { text, .. }
        | K::KeyboardButtonRequestGeoLocation { text, .. }
        | K::KeyboardButtonRequestPhone { text, .. }
        | K::Callback { text, .. }
        | K::Url { text, .. } => text.clone(),
        _ => String::new(),
    }
}
